version: "3"

services:

  addon-dev:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.dev
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://localhost:8080/Plone
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - backend
    tty: true
    profiles:
      - dev

  backend:
    image: plone/plone-backend:${PLONE_VERSION:-6}
    environment:
      SITE: Plone
      CORS_ALLOW_ORIGIN: '*'
    ports:
      - 8080:8080
    profiles:
      - dev
