name: Visual Regression Tests

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      short-name:
        required: true
        type: string
      node-version:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      storybook:
        required: true
        type: boolean

defaults:
  run:
    working-directory: ./frontend

env:
  CYPRESS_A11Y: true

jobs:

  visual-regression-tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout visual regression assets
        uses: actions/checkout@v4
        with:
          repository: kitconcept/vlt-visual-regression
          ref: playwright
          path: frontend/playwright/__screenshots__
          fetch-depth: 0

      - name: Load images
        if: ${{ inputs.storybook == false || inputs.storybook == 'false' || inputs.storybook == null }}
        run: |
          docker pull ${{ inputs.image-name-prefix }}-backend:${{ inputs.image-tag }}
          docker pull ${{ inputs.image-name-prefix }}-frontend:${{ inputs.image-tag }}
          docker image ls -a

      - uses: actions/download-artifact@v4
        if: ${{ inputs.storybook == true || inputs.storybook == 'true' }}
        with:
          name: storybook-build
          path: frontend/storybook-build

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Enable corepack
        run: npm i -g corepack@latest && corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install

      - name: Install Playwright browsers
        working-directory: frontend/packages/volto-light-theme
        run: pnpm exec playwright install --with-deps chromium

      # STORYBOOK TESTS
      - name: Start Servers - Storybook
        uses: JarvusInnovations/background-action@v1
        if: ${{ inputs.storybook == true || inputs.storybook == 'true' }}
        with:
          run: |
            python3 -m http.server 6006 -d frontend/storybook-build &
          wait-on: |
            http://localhost:6006
          tail: true # true = stderr,stdout
          log-output-resume: stderr
          wait-for: 10m
          log-output: stderr,stdout # same as true
          log-output-if: failure

      - name: Run visual regression tests Storybook
        if: ${{ inputs.storybook == true || inputs.storybook == 'true' }}
        run: pnpm exec playwright test playwright/tests/visual/storybook/${{ inputs.short-name }}.test.{js,jsx,ts,tsx}

      # Volto TESTS
      - uses: JarvusInnovations/background-action@v1
        if: ${{ inputs.storybook == false || inputs.storybook == 'false' || inputs.storybook == null }}
        name: Start Servers - Volto and Plone
        with:
          run: |
            docker run -i --net=host --rm --name=backend ${{ needs.config.outputs.image-name-prefix }}-backend:${{ needs.config.outputs.base-tag }} &
            docker run -i --net=host --rm --name=frontend -e RAZZLE_INTERNAL_API_PATH=http://localhost:8080/Plone ${{ needs.config.outputs.image-name-prefix }}-frontend:${{ needs.config.outputs.base-tag }} &

          wait-on: |
            http-get://localhost:8080/Plone
            http://localhost:3000

          tail: true # true = stderr,stdout

          log-output-resume: stderr

          wait-for: 10m

          log-output: stderr,stdout # same as true

          log-output-if: failure

      - name: Run visual regression tests - Volto
        if: ${{ inputs.storybook == false || inputs.storybook == 'false' || inputs.storybook == null }}
        run: pnpm exec playwright test playwright/tests/visual/main/${{ inputs.short-name }}.test.{js,jsx,ts,tsx}

      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright/results
